/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_obnsoft_arduboyemu_Native */

#ifndef _Included_com_obnsoft_arduboyemu_Native
#define _Included_com_obnsoft_arduboyemu_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    setup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_arduboyemu_Native_setup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    buttonEvent
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_obnsoft_arduboyemu_Native_buttonEvent
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    loop
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_arduboyemu_Native_loop
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    teardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_obnsoft_arduboyemu_Native_teardown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
