/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_obnsoft_arduboyemu_Native */

#ifndef _Included_com_obnsoft_arduboyemu_Native
#define _Included_com_obnsoft_arduboyemu_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    setup
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_arduboyemu_Native_setup
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    getEEPROM
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_obnsoft_arduboyemu_Native_getEEPROM
  (JNIEnv *, jclass);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    setEEPROM
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_arduboyemu_Native_setEEPROM
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    buttonEvent
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_obnsoft_arduboyemu_Native_buttonEvent
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    getLEDState
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_obnsoft_arduboyemu_Native_getLEDState
  (JNIEnv *, jclass);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    loop
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_arduboyemu_Native_loop
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_obnsoft_arduboyemu_Native
 * Method:    teardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_obnsoft_arduboyemu_Native_teardown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
